#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  9 01:40:42 2020

@author: jbl
"""

import senoidalTest as fxSen
import numpy as np


    x = mi_func_sen(1,0,1,100,100)  
    N = x.size
    n = np.arange(N)
    k = n.reshape((N, 1))
    e = np.exp(-2j * np.pi * k * n / N)
    fft = np.dot(e, x)